language: generic
sudo: required
services:
  - docker

before_intsall:
  - docker build -t docker-ci -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-ci npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-966253814118"
  bucket_path: "docker-react"
  on:
    branch: master

  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY