FROM node:16-alpine

RUN echo "timeout=60000" >> /usr/local/lib/node_modules/npm/.npmrc
RUN npm install -g npm@8.6.0

USER node

RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./
RUN npm install

COPY --chown=node:node ./ ./

CMD ["npm", "run", "start"]